#!/bin/bash

# Uso: target


ARCHIVO="/tmp/ip_target.txt"

# Si se pasa la opción --clear, borra el archivo y sale
if [[ "$1" == "-c" ]]; then
  rm -f "$ARCHIVO"
  echo "Archivo temporal eliminado."
  exit 0
fi


if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Uso: target <nombre> <ip>  o  target --clear"
  exit 1
fi

NOMBRE=$1
IP=$2


# Escribe en un archivo temporal que el Panel va a leer
echo "󰓾  $NOMBRE - $IP" > $ARCHIVO